apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: boinc-60
  namespace: bu528-stop-wasting-the-cloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wcg
  template:
    metadata:
      labels:
        app: wcg
    spec:
      nodeName: k008
      containers:
      - name: latest
        image: anshugoe/centos-boinc
        ports:
          - containerPort: 8080
        resources:
          requests:
            cpu: "1"
            memory: "5Gi"
          limits:
            cpu: "6"
            memory: "24Gi"
        env:
        - name: boincurl
          valueFrom:
            configMapKeyRef:
              name: boinc-url-key
              key: boincurl
        - name: boinckey
          valueFrom:
            configMapKeyRef:
              name: boinc-url-key
              key: boinckey